version: '3'
services:

  # MySQL service
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: EspritHub
    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  # Spring Boot service
  springboot-app:
    image: malekzeghouf/backendfractusdeploy
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      SPRING_APPLICATION_JSON: >-
        {
          "spring.datasource.url": "jdbc:mysql://mysql:3306/EspritHub?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto": "update"        }
      tty: true


volumes:
  mysql-data:
